/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ghgame_javausecpp_JavaUseCpp */

#ifndef _Included_com_ghgame_javausecpp_JavaUseCpp
#define _Included_com_ghgame_javausecpp_JavaUseCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ghgame_javausecpp_JavaUseCpp
 * Method:    printStr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ghgame_javausecpp_JavaUseCpp_printStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ghgame_javausecpp_JavaUseCpp
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_ghgame_javausecpp_JavaUseCpp_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
