/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_ccsu_graduationproject_businquiry_service_impl_QueryServiceImpl */

#ifndef _Included_cn_ccsu_graduationproject_businquiry_service_impl_QueryServiceImpl
#define _Included_cn_ccsu_graduationproject_businquiry_service_impl_QueryServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ccsu_graduationproject_businquiry_service_impl_QueryServiceImpl
 * Method:    getStrategies
 * Signature: ([Lcn/ccsu/graduationproject/businquiry/entities/Line;[Lcn/ccsu/graduationproject/businquiry/entities/Station;[Lcn/ccsu/graduationproject/businquiry/entities/Route;Ljava/lang/String;Ljava/lang/String;)[Lcn/ccsu/graduationproject/businquiry/entities/Strategy;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_ccsu_graduationproject_businquiry_service_impl_QueryServiceImpl_getStrategies
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
